"""add expiration_date to client

Revision ID: 455dc1ed6e34
Revises: ea559b2a3230
Create Date: 2026-07-08 15:11:00.196176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455dc1ed6e34'
down_revision = 'ea559b2a3230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
