"""Add firm settings model

Revision ID: 53cc378e201e
Revises: 912b3579c19a
Create Date: 2026-07-10 06:15:50.213964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cc378e201e'
down_revision = '912b3579c19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firm_settings')
    # ### end Alembic commands ###
