"""add upload session and upload id

Revision ID: 845197578ae5
Revises: 384cdeab7b84
Create Date: 2026-07-08 01:34:04.672046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845197578ae5'
down_revision = '384cdeab7b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('successful_uploads', sa.Integer(), nullable=False),
    sa.Column('failed_uploads', sa.Integer(), nullable=False),
    sa.Column('duplicate_files', sa.Integer(), nullable=False),
    sa.Column('unknown_clients', sa.Integer(), nullable=False),
    sa.Column('approval_requests_created', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('upload_session_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_session_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_session_files_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.String(length=20), nullable=True))
        
    # Populate existing clients with upload_id
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM client_profiles WHERE upload_id IS NULL")).fetchall()
    
    if result:
        import random
        import string
        
        for row in result:
            client_id = row[0]
            # Generate unique CLI-XXXXXX
            while True:
                chars = string.ascii_uppercase + string.digits
                suffix = ''.join(random.choices(chars, k=6))
                uid = f"CLI-{suffix}"
                
                res = connection.execute(
                    sa.text("SELECT id FROM client_profiles WHERE upload_id = :uid"),
                    {"uid": uid}
                ).fetchone()
                
                if not res:
                    connection.execute(
                        sa.text("UPDATE client_profiles SET upload_id = :uid WHERE id = :id"),
                        {"uid": uid, "id": client_id}
                    )
                    break

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_profiles_upload_id'), ['upload_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_profiles_upload_id'))
        batch_op.drop_column('upload_id')

    with op.batch_alter_table('upload_session_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_session_files_session_id'))

    op.drop_table('upload_session_files')
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_user_id'))

    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
