"""add document files table

Revision ID: 912b3579c19a
Revises: 455dc1ed6e34
Create Date: 2026-07-10 00:36:40.497306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912b3579c19a'
down_revision = '455dc1ed6e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_files_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('cloudinary_public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cloudinary_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cloudinary_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cloudinary_public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_files_document_id'))

    op.drop_table('document_files')
    # ### end Alembic commands ###
