"""Remove unique constraint from document file_hash

Revision ID: bbe514a3d50f
Revises: 13f2d4ab8c08
Create Date: 2026-07-08 07:43:25.004538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe514a3d50f'
down_revision = '13f2d4ab8c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=True)

    # ### end Alembic commands ###
