"""Add invoice defaults to FirmSettings

Revision ID: d913e81c8e6a
Revises: 0f0a5b48b2ea
Create Date: 2026-07-10 06:56:32.082713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd913e81c8e6a'
down_revision = '0f0a5b48b2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firm_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gstin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('default_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm_settings', schema=None) as batch_op:
        batch_op.drop_column('default_notes')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('gstin')
        batch_op.drop_column('firm_address')

    # ### end Alembic commands ###
