"""make file_hash nullable

Revision ID: ea559b2a3230
Revises: bbe514a3d50f
Create Date: 2026-07-08 13:11:00.393413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea559b2a3230'
down_revision = 'bbe514a3d50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
