from datetime import datetime, timezone
from ..extensions import db

class ApprovalRequest(db.Model):
    """
    Approval workflow requests generated by employee actions.
    """
    __tablename__ = 'approval_requests'

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, index=True)
    document_id = db.Column(db.Integer, db.ForeignKey('documents.id', ondelete='SET NULL'), nullable=True, index=True)
    
    request_type = db.Column(db.String(50), nullable=False) # 'Upload', 'Replace', 'Metadata Edit', 'Delete', 'Password Change'
    
    # Store JSON representation of states
    previous_values = db.Column(db.Text, nullable=True)
    proposed_values = db.Column(db.Text, nullable=False)
    
    rejection_reason = db.Column(db.Text, nullable=True)
    status = db.Column(db.String(20), default='Pending', nullable=False, index=True) # Pending / Approved / Rejected
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    reviewed_at = db.Column(db.DateTime, nullable=True)
    reviewed_by_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)

    # Relationships
    employee = db.relationship('User', foreign_keys=[employee_id], backref='sent_requests')
    reviewer = db.relationship('User', foreign_keys=[reviewed_by_id], backref='reviewed_requests')
    document = db.relationship('Document', backref=db.backref('approval_requests', cascade='all, delete-orphan'))

    def __repr__(self):
        return f'<ApprovalRequest {self.request_type} - {self.status}>'
